version: '3.4'

services:
  dockermicros:
    image: ${DOCKER_REGISTRY-}dockermicros
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    depends_on:
        - db_service
    networks:
        - db-network

  db_service:
    container_name: db_service
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Maqsudkhan
      - POSTGRES_DB=MicroserviceDockerDB
    volumes:
      - pgdata:/var/lib/postgresql/MicroserviceDockerDB
    ports:
      - "5432:5432"

networks:
  db-network:
    driver: bridge

volumes:
  pgdata:
