version: '3.4'

services:
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
        - db_service
    depends_on:
        - db
    networks:
        - db-network

  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Maqsudkhan
      - POSTGRES_DB=MicrosrviceDockerDB
    volumes:
      - pgdata:/var/lib/postgresql/MicrosrviceDockerDB
    ports:
      - "5432:5432" 
    networks:
      - db-network


networks:
  db-network:
    driver: bridge

volumes:
  pgdata:



#   version: '3.4'

# services:
#   catalog.api:
#     image: ${DOCKER_REGISTRY-}catalogapi
#     build:
#       context: .
#       dockerfile: src/Catalog/Catalog.API/Dockerfile
#     depends_on:
#       - db
#     networks:
#       - db-network
#   db:
#     container_name: db
#     image: postgres:latest
#     environment:
#       - POSTGRES_USER=user
#       - POSTGRES_PASSWORD=coder
#       - POSTGRES_DB=ECommerceCatalog.DB
#     volumes:
#       - pgdata:/var/lib/postgresql/ECommerceCatalog.DB
#     ports:
#       - "5432:5432"
#     networks:
#       - db-network    
 

# networks:
#   db-network:
#     driver: bridge

# volumes:
#   pgdata:

   